// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
// /// // ...
//    Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkSzMWBRPamyH-FgfFFOZMI2UYaVMHBQ',
    appId: '1:595982245991:web:502a605c975455bde9b4c2',
    messagingSenderId: '595982245991',
    projectId: 'loyaltiy-b31ac',
    authDomain: 'loyaltiy-b31ac.firebaseapp.com',
    storageBucket: 'loyaltiy-b31ac.appspot.com',
    measurementId: 'G-9FK53RX8H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3i2zfL6roZzdiRFmJxBFz_ms7amo1M_0',
    appId: '1:595982245991:android:533dff78a9bea733e9b4c2',
    messagingSenderId: '595982245991',
    projectId: 'loyaltiy-b31ac',
    storageBucket: 'loyaltiy-b31ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNLwszKt4k42nCKG6eur1Tmf4aIvU6RvI',
    appId: '1:595982245991:ios:32c1fff6c084ca67e9b4c2',
    messagingSenderId: '595982245991',
    projectId: 'loyaltiy-b31ac',
    storageBucket: 'loyaltiy-b31ac.appspot.com',
    iosBundleId: 'com.example.loyaltySystemMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNLwszKt4k42nCKG6eur1Tmf4aIvU6RvI',
    appId: '1:595982245991:ios:32c1fff6c084ca67e9b4c2',
    messagingSenderId: '595982245991',
    projectId: 'loyaltiy-b31ac',
    storageBucket: 'loyaltiy-b31ac.appspot.com',
    iosBundleId: 'com.example.loyaltySystemMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpkSzMWBRPamyH-FgfFFOZMI2UYaVMHBQ',
    appId: '1:595982245991:web:9aaf322a696958fde9b4c2',
    messagingSenderId: '595982245991',
    projectId: 'loyaltiy-b31ac',
    authDomain: 'loyaltiy-b31ac.firebaseapp.com',
    storageBucket: 'loyaltiy-b31ac.appspot.com',
    measurementId: 'G-VBGJVWZ4D8',
  );
}
